name: Pheonix Test Automation Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to run tests against"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - uat
          - dev
      testng_suite:
        description: "Select TestNG suite file to run"
        required: true
        default: "testng.xml"
        type: choice
        options:
          - testng.xml
          - smoke.xml
          - regression.xml
          - testng-datadriven.xml
permissions:
        contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Create .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > .env
          echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}" >> .env
          echo "DB_USER_PASSWORD=${{ secrets.DB_USER_PASSWORD }}" >> .env

      - name: Execute test automation framework
        run: |
          mvn clean test \
            -DsuiteXmlFile=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.testng_suite || 'testng.xml' }} \
            -Denv=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'qa' }}
      - name: Generating Allure Report
        if: always()
        run: mvn allure:report
      - name: creating github branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
             github_token: ${{secrets.GITHUB_TOKEN}}
             publish_dir: .target/site/allure-maven-plugin
      
      - name: Upload Surefire Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire Report
          path: target/surefire-reports
          retention-days: 10
